# Generated by Django 4.1.7 on 2023-03-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='名字'),
        ),
    ]
