# Generated by Django 4.1.7 on 2023-04-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django02', '0002_alter_bookinfo_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peopleinfo',
            options={'verbose_name': '人物'},
        ),
    ]
